name: Ubuntu

on: [push, pull_request]

permissions:
  contents: read

jobs:
  gcc_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_gcc
      run: |
           sudo apt update
           sudo apt install gcc-10 g++-10
      shell: bash
    - name: cmake
      run: cmake -S . -B build -DJSONCONS_SANITIZE=ON -DCMAKE_BUILD_TYPE=Debug -DJSONCONS_BUILD_TESTS=On
      env:
        CC:   gcc-10
        CXX:  g++-10
    - name: build
      run: cmake --build build --parallel 10
    - name: test
      run: cd build ; ctest -j 10 --output-on-failure

  gcc_build_no_deprecated:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_gcc
      run: |
           sudo apt update
           sudo apt install gcc-10 g++-10
      shell: bash
    - name: cmake
      run: cmake -S . -B build -DCXXFLAGS="-DJSONCONS_NO_DEPRECATED" -DCMAKE_BUILD_TYPE=Debug -DJSONCONS_BUILD_TESTS=On
      env:
        CC:   gcc-10
        CXX:  g++-10
    - name: build
      run: cmake --build build --parallel 10
    - name: test
      run: cd build ; ctest -j 10 --output-on-failure

  clang_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_gcc
      run: |
           sudo apt update
           sudo apt install clang-10
      shell: bash
    - name: cmake
      run: cmake -S . -B build -DJSONCONS_SANITIZE=ON -DCMAKE_BUILD_TYPE=Debug -DJSONCONS_BUILD_TESTS=On
      env:
        CC:   clang-10
        CXX:  clang++-10
    - name: build
      run: cmake --build build --parallel 10
    - name: test
      run: cd build ; ctest -j 10 --output-on-failure

  clang_build_cxx20:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_gcc
      run: |
           sudo apt update
           sudo apt install clang-10
      shell: bash
    - name: cmake
      run: cmake -S . -B build -DJSONCONS_SANITIZE=ON -DCMAKE_BUILD_TYPE=Debug -DJSONCONS_BUILD_TESTS=On -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON
      env:
        CC:   clang-10
        CXX:  clang++-10
    - name: build
      run: cmake --build build --parallel 10
    - name: test
      run: cd build ; ctest -j 10 --output-on-failure

  gcc_build_48:
    name: GCC 4.8
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install
      run: |
           sudo apt-get update -y -qq && sudo apt-get install -y -qq g++-4.8 binutils
      shell: bash
    - name: cmake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DJSONCONS_BUILD_TESTS=On
      env:
        CC:   gcc-4.8
        CXX:  g++-4.8
    - name: build
      run: cmake --build build --parallel 10
    - name: test
      run: cd build ; ctest -j 10 --output-on-failure


